/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.naes.main;

import com.formdev.flatlaf.FlatLightLaf;
import com.naes.utils.AuthenticationService;
import com.naes.utils.LoginResult;
import com.naes.models.User;
import com.naes.utils.ValidationResult;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.concurrent.ExecutionException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author seany
 */
public class Main extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());
    
    private javax.swing.Timer loadingTimer;
    private int dotCount = 0;
    private String loadingBaseMessage = "";

    private volatile boolean isLoading = false;
    private boolean isSaved;
    
    private static final int MESSAGE_LABEL_HEIGHT = 40;
    private static final int MESSAGE_LABEL_WIDTH = 310;
    int originalLoginContainerHeight;
    
    /**
     * Creates new form MainPanel
     */
    public Main() {
        initComponents();
        messageLabel.setVisible(false);
        originalLoginContainerHeight = loginContainer.getPreferredSize().height;
        addEnterKeyListener();
        setupDividerPanel();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dividerPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginContainer = new javax.swing.JPanel();
        loginHeader = new javax.swing.JPanel();
        appIconLabel = new javax.swing.JLabel();
        appNameLabel = new javax.swing.JLabel();
        signInButton = new com.naes.swing.Button();
        showPassword = new javax.swing.JCheckBox();
        usernameTextField = new com.naes.swing.TextField();
        passwordTextField = new com.naes.swing.PasswordField();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Student Information System");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1012, 612));

        dividerPanel.setOpaque(false);

        javax.swing.GroupLayout dividerPanelLayout = new javax.swing.GroupLayout(dividerPanel);
        dividerPanel.setLayout(dividerPanelLayout);
        dividerPanelLayout.setHorizontalGroup(
            dividerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        dividerPanelLayout.setVerticalGroup(
            dividerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        loginPanel.setOpaque(false);

        loginContainer.setOpaque(false);

        loginHeader.setOpaque(false);

        appIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/naes/icons/school.png"))); // NOI18N

        appNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        appNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appNameLabel.setText("Student Information System");

        javax.swing.GroupLayout loginHeaderLayout = new javax.swing.GroupLayout(loginHeader);
        loginHeader.setLayout(loginHeaderLayout);
        loginHeaderLayout.setHorizontalGroup(
            loginHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(appNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginHeaderLayout.setVerticalGroup(
            loginHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginHeaderLayout.createSequentialGroup()
                .addComponent(appIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(appNameLabel)
                .addGap(0, 0, 0))
        );

        signInButton.setBackground(new java.awt.Color(102, 102, 255));
        signInButton.setForeground(new java.awt.Color(255, 255, 255));
        signInButton.setText("Sign in");
        signInButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        showPassword.setBackground(new java.awt.Color(255, 255, 255));
        showPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        showPassword.setText("Show Password?");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        usernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameTextField.setLabelText("Username");
        usernameTextField.setName(""); // NOI18N

        passwordTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordTextField.setLabelText("Password");

        messageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray)));

        javax.swing.GroupLayout loginContainerLayout = new javax.swing.GroupLayout(loginContainer);
        loginContainer.setLayout(loginContainerLayout);
        loginContainerLayout.setHorizontalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showPassword)
                    .addComponent(signInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        loginContainerLayout.setVerticalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(loginContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(loginContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dividerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dividerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(!isSaved) {
            int choice = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to exit without saving?",
                    "Warning", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.WARNING_MESSAGE);
            if (choice == JOptionPane.YES_OPTION) {
                System.exit(0); // Exit without saving last changes
            }
            //Save changes and then exit
        }
        System.exit(0); // Exits if all recent changes is saved
    }//GEN-LAST:event_formWindowClosing

    // <editor-fold defaultstate="collapsed" desc="Loading Methods">
    private void showLoading(String message) {
        loadingBaseMessage = message;
        dotCount = 0;
        isLoading = true;
        
        enableDividerPanel();
        
        messageLabel.setIcon(null);
        messageLabel.setForeground(new java.awt.Color(51, 102, 255));
        messageLabel.setText(message + ".");
        messageLabel.setPreferredSize(new Dimension(MESSAGE_LABEL_WIDTH, MESSAGE_LABEL_HEIGHT));
        messageLabel.setVisible(true);
        resizeLoginContainer();
        
        loadingTimer = new javax.swing.Timer(500, e -> {
            if (isLoading) {
                dotCount = (dotCount % 3) + 1;
                String dots = ".".repeat(dotCount);
                messageLabel.setText(loadingBaseMessage + dots);
            }
        });
        loadingTimer.start();
    }
    
    private void hideLoading() {
        isLoading = false;
        
        disableDividerPanel();
        
        if (loadingTimer != null) {
            loadingTimer.stop();
            loadingTimer = null;
        }

        dotCount = 0;
        loadingBaseMessage = "";
        messageLabel.setForeground(new java.awt.Color(0, 0, 0)); // Reset to red for errors
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Message Methods">
    private void loadImage(String image) {
        
        ImageIcon imageIcon;
        try {
            switch(image) {
                case "warning" -> { 
                    imageIcon = new ImageIcon(getClass().getResource("/com/naes/icons/caution.png")); 
                    messageLabel.setForeground(new java.awt.Color(0, 0, 0));
                }
                case "error" -> { 
                    imageIcon = new ImageIcon(getClass().getResource("/com/naes/icons/error.png"));
                    messageLabel.setForeground(new java.awt.Color(204, 0, 0)); 
                }
                default -> { imageIcon = null;
                    messageLabel.setForeground(new java.awt.Color(0, 0, 0));
                }
            }
            
            messageLabel.setIcon(imageIcon);
        } catch (Exception e) {
            logger.log(java.util.logging.Level.WARNING, "Could not load icon: " + image, e);
        }
    }
    
    private void showMessage(String message, String icon) {
        hideLoading();
        loadImage(icon);
        messageLabel.setText(message);
        messageLabel.setPreferredSize(new Dimension(MESSAGE_LABEL_WIDTH, MESSAGE_LABEL_HEIGHT));
        messageLabel.setVisible(true);
        resizeLoginContainer();
    }
    
    private void hideMessage() {
        hideLoading();
        messageLabel.setVisible(false);
        messageLabel.setPreferredSize(new Dimension(MESSAGE_LABEL_WIDTH, 0));
        resetLoginContainerSize();
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Container Methods">
    private void resizeLoginContainer() {
        Dimension currentSize = loginContainer.getPreferredSize();
        loginContainer.setPreferredSize(new Dimension(currentSize.width, originalLoginContainerHeight + MESSAGE_LABEL_HEIGHT));
        refreshLoginContainer();
    }
    
    private void resetLoginContainerSize() {
        Dimension currentSize = loginContainer.getPreferredSize();
        loginContainer.setPreferredSize(new Dimension(currentSize.width, originalLoginContainerHeight));
        refreshLoginContainer();
    }
    
    private void refreshLoginContainer() {
        loginContainer.revalidate();
        loginContainer.repaint();
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Login Methods">
    private ValidationResult validateLogin() {
        String username = usernameTextField.getText().trim();
        String password = String.valueOf(passwordTextField.getPassword());
        
        if (username.isEmpty() && password.isEmpty()) {
            usernameTextField.grabFocus();
            return ValidationResult.failed("Please fill out the missing fields.");
        }
        
        if (!username.isEmpty() && password.isEmpty()) {
            passwordTextField.grabFocus();
            return ValidationResult.failed("Please fill out password field.");
        }
        
        if (username.isEmpty() && !password.isEmpty()) {
            usernameTextField.grabFocus();
            return ValidationResult.failed("Please fill out username field.");
        }
        return ValidationResult.success();  
    }
    
    private void loginInBackground(String username, String password) {
        new javax.swing.SwingWorker<LoginResult, Void>() {

            @Override
            protected LoginResult doInBackground() {
                AuthenticationService authService = new AuthenticationService();
                return authService.loginUser(username, password);
            }

            @Override
            protected void done() {
                try {
                    LoginResult result = get();
                    afterLogin(result);
                } catch (InterruptedException | ExecutionException e) {
                    logger.log(java.util.logging.Level.SEVERE, "Login error", e);
                    onLoginError();
                }
            }
        }.execute();
    }
    
    private void afterLogin(LoginResult result) {
        hideLoading();
        signInButton.setText("Sign in");

        if (result.isSuccess()) {
            onLoginSuccess(result.getUser());
        } else {
            onLoginFailed(result.getMessage());
        }
    }

    private void onLoginSuccess(User user) {
        hideMessage();
        passwordTextField.setText("");
        System.out.println("User: " + user.getUsername() + " successfully logged in.");
        this.dispose();
    }

    private void onLoginFailed(String errorMessage) {
        showMessage(errorMessage, "error");
        passwordTextField.setText("");
        passwordTextField.grabFocus();
    }

    private void onLoginError() {
        hideLoading();
        signInButton.setEnabled(true);
        signInButton.setText("Sign in");
        showMessage("Something went wrong. Please try again.", "error");
        passwordTextField.setText("");
        passwordTextField.grabFocus();
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Blocker Methods">
    private void setupDividerPanel() {
        dividerPanel.setVisible(false);
        dividerPanel.setFocusable(true);
        dividerPanel.setFocusCycleRoot(true);
        MouseAdapter mouseBlocker = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                e.consume();
            }
            
            @Override
            public void mousePressed(MouseEvent e) {
                e.consume();
            }
            
            @Override
            public void mouseReleased(MouseEvent e) {
                e.consume();
            }
        };
        dividerPanel.addMouseListener(mouseBlocker);
    }
    
    private void enableDividerPanel() {
        usernameTextField.setFocusable(false);
        passwordTextField.setFocusable(false);
        showPassword.setFocusable(false);
        signInButton.setFocusable(false);
        dividerPanel.setVisible(true);
        dividerPanel.requestFocusInWindow();
    } 
    
    private void disableDividerPanel() {
        usernameTextField.setFocusable(true);
        passwordTextField.setFocusable(true);
        showPassword.setFocusable(true);
        signInButton.setFocusable(true);
        dividerPanel.setVisible(false);
    }
    // </editor-fold>
    
    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        if (dividerPanel.isVisible()) {
            return;
        }
        
        ValidationResult validationResult = validateLogin();
        
        if(!validationResult.isValid()) {
            showMessage(validationResult.getErrorMessage(), "warning");
            return;
        }
        
        signInButton.setText("Signing in");
        showLoading("Signing in, please wait");
        String username = usernameTextField.getText().trim();
        String password = String.valueOf(passwordTextField.getPassword());
        
        loginInBackground(username, password);
    }//GEN-LAST:event_signInButtonActionPerformed
    
    private void togglePasswordVisibility() {
        if (showPassword.isSelected()) {
            passwordTextField.setEchoChar((char) 0);
        } else {
            passwordTextField.setEchoChar('*');
        }
    }
    
    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if (dividerPanel.isVisible()) {
            return;
        }
        togglePasswordVisibility();
    }//GEN-LAST:event_showPasswordActionPerformed
    
    private void addEnterKeyListener() {
        java.awt.event.KeyAdapter enterKeyListener = new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    signInButton.doClick();
                }
            }
        };
        usernameTextField.addKeyListener(enterKeyListener);
        passwordTextField.addKeyListener(enterKeyListener);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appIconLabel;
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JPanel dividerPanel;
    private javax.swing.JPanel loginContainer;
    private javax.swing.JPanel loginHeader;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel messageLabel;
    private com.naes.swing.PasswordField passwordTextField;
    private javax.swing.JCheckBox showPassword;
    private com.naes.swing.Button signInButton;
    private com.naes.swing.TextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
